Inventory to cloud chamber
Jim3Things/CloudChamber pull request #154
Opened 2020-09-17 19:01 UTC by manpreet85

1. Updated Inventory.Yaml to represent 8 racks and each rack having 8 blades.
2. Updating DBInventory.go so that the Inventory is read from the external defintion file.

2020-09-17 19:16 UTC, Jim3Things commented on internal/services/frontend/DBInventory.go
> +func (m *DBInventory) GetMemoData() (int64, *common.BladeCapacity) {
The change to add this was made in the recent checkins, and inventory.go depends on it.  Was removing it intentional?

2020-09-17 19:20 UTC, manpreet85 commented on internal/services/frontend/DBInventory.go
> +func (m *DBInventory) GetMemoData() (int64, *common.BladeCapacity) {
Unintentional. 

Should I reenter and send for PR

2020-09-17 23:28 UTC, Jim3Things commented on internal/services/frontend/DBInventory.go
> +func (m *DBInventory) GetMemoData() (int64, *common.BladeCapacity) {
Sure.

2020-09-18 20:58 UTC, MikeCJohnsonUk requested changes

2020-09-18 20:58 UTC, MikeCJohnsonUk commented on internal/services/frontend/DBInventory.go
> +func (m *DBInventory) GetMemoData() (int64, *common.BladeCapacity) {
Looks like an older version? We're missing the "int" return value in the declaration, and the associated returned value on line 174

2020-09-18 20:58 UTC, MikeCJohnsonUk commented on internal/services/frontend/DBInventory.go
> +//We need dbinventory to create the inventory via the inventory reader
Do we need to retain these comments?

2020-09-19 05:39 UTC, Jim3Things approved these changes

2020-09-19 05:39 UTC, MikeCJohnsonUk approved these changes

2020-09-19 05:45 UTC, merged