Initial pass at storing inventory definition in the store
Jim3Things/CloudChamber pull request #181
Opened 2020-11-12 19:53 UTC by MikeCJohnsonUk

This is still a work-in-progress and is not yet active in production.
This change contains the protobuf file for the definition, create and read routines for zones, racks, pdus, tors, and blades along with some basic tests to exercise the create and read functionality. It also includes templates for subsequent routines for update and delete.

Also included is the planned WithXxxx() option modifiers as templates, but as yet these are not active.

There are also a number of routines which have been added in preparation for future changes but which are not yet active.

The purpose of this PR is publish the intentions for this chunk of feature set to ensure everything is headed in the right direction.

Next steps
- add tests for the UpdateXxxx() routines and ensure everything works as expected
- add tests for the DeleteXxxx() routines and ensure everything works as expected
- add the body for the ListXxxx() routines along with tests to ensure everything works as expected
- add ability to read the definition from a file, and update the store to match the file content.
- add the ability to specify the WithRevision() option for ReadXxx() and ListXxxx() routines.
- add the ability to specify the WithRevision() option for UpdateXxx() and DeleteXxxx() routines.
- cut-over from current inventory definition load to store based inventory definitions.

2020-11-12 22:57 UTC, Jim3Things requested changes

2020-11-12 22:57 UTC, Jim3Things commented on internal/clients/store/storeapi.go
> +/*
I know that we're using IDEs that colorize, but this seems a bit subtle of a trigger for noticing that this whole section is actually a comment.  Can you make it more visible?

2020-11-12 22:57 UTC, Jim3Things commented on internal/clients/store/storeapi.go
> +	if err != nil {
Can't this be folded up into the check at line 372?  I think that if it ever falls out of the loop at 373 it will end up at line 382...

2020-11-12 22:57 UTC, Jim3Things commented on internal/clients/store/storeapi.go
> +	// Need to strip the namespace prefix and return something described
Nit: can you specify that this only applies to the loop below?

2020-11-12 22:57 UTC, Jim3Things commented on internal/clients/store/storeapi.go
> +func (store *Store) Update(ctx context.Context, r KeyRoot, n string, rev int64,	v string) (revision int64, err error) {
odd spacing

2020-11-12 22:57 UTC, Jim3Things commented on internal/config/InventoryReader.go
> +		span.AddEvent(ctx, err.Error())
Glad to see the conversion to the CC tracing library - the AddEvent calls should also be converting to tracing.Error (or other tracing.Xxx, depending)

2020-11-12 22:57 UTC, Jim3Things commented on internal/config/InventoryReader.go
> +	//and a set of blades.
nit: spacing.

2020-11-12 22:57 UTC, Jim3Things commented on internal/config/InventoryReader.go
> +					Port: 0,
Is this right?  Shouldn't something point to the blade?

2020-11-12 22:57 UTC, Jim3Things commented on internal/config/InventoryReader.go
> +					Port: 0,
ditto

2020-11-12 22:57 UTC, Jim3Things commented on internal/config/InventoryReader_test.go
> +
fewer blank lines

2020-11-12 22:57 UTC, Jim3Things commented on internal/config/InventoryReader_test.go
> +
Test the cables somewhere in here.

2020-11-12 22:57 UTC, Jim3Things commented on internal/services/frontend/DBInventory.go
> +func InitDBInventory(ctx context.Context, cfg *config.GlobalConfig) (err error) {
Would it be easier to test, and if so, is this a good time, to have Init return a pointer to the struct, rather than assume the global?

2020-11-12 22:57 UTC, Jim3Things commented on internal/services/frontend/DBInventory.go
> +	for name := range m.Zone.Racks {
good catch!

2020-11-12 22:57 UTC, Jim3Things commented on pkg/protos/inventory/external.proto
> +import "pkg/protos/common/capacity.proto";
Why this change?

2020-11-12 22:57 UTC, Jim3Things commented on pkg/protos/inventory/definition.proto
> +message zonemap {
Nit, but might be better as either 'zones' or 'zone_map'

2020-11-12 22:57 UTC, Jim3Things commented on pkg/protos/inventory/definition.Validate.go
> +func(x *DefinitionTor) Verify() error {
Who calls Verify, and is there a reason why it is not part of the normal Validate processing?

2020-11-12 22:57 UTC, Jim3Things commented on pkg/protos/inventory/definition.proto
> +import "pkg/protos/common/capacity.proto";
We use the full path elsewhere, I'm not sure why the short path here?

2020-11-25 20:19 UTC, MikeCJohnsonUk commented on internal/clients/store/storeapi.go
> +/*
Done

2020-11-25 20:19 UTC, MikeCJohnsonUk commented on internal/clients/store/storeapi.go
> +	if err != nil {
Yup. Done.

2020-11-25 20:20 UTC, MikeCJohnsonUk commented on internal/clients/store/storeapi.go
> +	// Need to strip the namespace prefix and return something described
Makes sense. Done.

2020-11-25 20:24 UTC, MikeCJohnsonUk commented on internal/clients/store/storeapi.go
> +func (store *Store) Update(ctx context.Context, r KeyRoot, n string, rev int64,	v string) (revision int64, err error) {
Ha! An embedded tab which with all my editors hid itself. Good spot.

Fixed,

2020-11-25 20:36 UTC, MikeCJohnsonUk commented on internal/config/InventoryReader.go
> +		span.AddEvent(ctx, err.Error())
I've fixed this and converted the others. I believe I have the usage correct, but would appreciate the confirmation.

Done.

2020-11-25 20:36 UTC, MikeCJohnsonUk commented on internal/services/frontend/DBInventory.go
> +	for name := range m.Zone.Racks {
Yeah, I was pleased with myself on this one.

2020-11-25 20:37 UTC, MikeCJohnsonUk commented on internal/config/InventoryReader.go
> +	//and a set of blades.
Done.

2020-11-25 20:45 UTC, MikeCJohnsonUk commented on internal/config/InventoryReader.go
> +					Port: 0,
Correct. What the 'Item' here should be is something along the lines of

				Item:  &pb.DefinitionItem{
					Type: pb.DefinitionItem_blade,
					Id: b.Index,
					Port: 0,
					},
which says that this pdu port we are adding is connected to a blade with index b.Index and port 0 (for now) on that blade. There is an analogous construct for the tor.

2020-11-25 21:16 UTC, MikeCJohnsonUk commented on internal/config/InventoryReader_test.go
> +
Done.

2020-11-25 21:27 UTC, MikeCJohnsonUk commented on pkg/protos/inventory/external.proto
> +import "pkg/protos/common/capacity.proto";
Took me a while to remember.

In the new definition.proto file, if I use the full path, the CLI driven compilation is fine, but VsCode objects claiming the file "was not found or had errors".

In this location, with the same import path, everything looks fine and I removed the prefix to see what impact it had, the answer being none. I just neglected to revert this change.

Not sure what to do with the import path in definition.proto though. I'm open to suggestions. though.

2020-11-25 22:04 UTC, MikeCJohnsonUk commented on pkg/protos/inventory/external.proto
> +import "pkg/protos/common/capacity.proto";
Update: it seems VsCode also complains here with the prefixed import path.

I've done some digging around, and I *think* the import path should be a relative directory path rather than a package name. That is, I believe we should be using 

import "pkg/protos/common/capacity.proto";

and not, as we currently have

import "github.com/Jim3Things/CloudChamber/pkg/protos/common/capacity.proto";

The "option go_package= xxx" should remain unchanged.


I suspect you may have been using an IDEA option to locate the proto files somewhere?

2020-11-25 22:22 UTC, MikeCJohnsonUk commented on pkg/protos/inventory/definition.proto
> +import "pkg/protos/common/capacity.proto";
See discussion above, but in summary, I believe this is a file path reference, and not a package location and so should be relative to the base of the project directory.

2020-11-27 23:35 UTC, MikeCJohnsonUk commented on pkg/protos/inventory/definition.proto
> +message zonemap {
changed to "region" as it is somewhat more relevant!

2020-11-27 23:37 UTC, MikeCJohnsonUk commented on pkg/protos/inventory/definition.Validate.go
> +func(x *DefinitionTor) Verify() error {
I was calling it under slightly different circumstance which didn't have the same requirements as validate.

I've changed this to be a common internal routine which does all the validation and then a couple of outer functions dealing the the parameters differences and a simple specialization in one case. This means both parts get the complete generalized check.

I think this fixes the problem.

2020-11-28 01:56 UTC, Jim3Things commented on internal/config/InventoryReader.go
> +			Location:  "DC-PNW-0",
Fyi: this would be best to be a string constant, as I expect the location is going to ultimately either come from inventory def yaml or from config.

2020-11-28 01:56 UTC, Jim3Things commented on internal/services/frontend/DBInventory.go
> +func (m *DBInventory) ListBlades(ctx context.Context, zone string, rack string, options ...InventoryOption) (map[string]*DefinitionBlade, int64, error) {return nil, InvalidRev, nil}
Nit: formatting - lines too long...

2020-11-28 01:56 UTC, Jim3Things commented on internal/services/frontend/DBInventory_test.go
> +// 	assert := ts.Assert()
Presumably these commented out lines will be deleted at some point?

2020-11-28 01:56 UTC, Jim3Things commented on internal/services/frontend/frontend.go
>  	ts "github.com/Jim3Things/CloudChamber/internal/clients/timestamp"
aren't these duplicates?

2020-11-28 01:56 UTC, Jim3Things commented on pkg/protos/common/errors.go
> +// ErrInvalidItemSelf signals that the specified item has wired a port to itsel.
itself.

2020-11-28 01:56 UTC, Jim3Things commented on pkg/protos/inventory/definition.Validate.go
> +func(x *DefinitionTor) Verify() error {
ok

2020-11-28 01:56 UTC, Jim3Things commented on pkg/protos/inventory/external.proto
> +import "pkg/protos/common/capacity.proto";
we followed up offline - the issue I had previously was due to the pre-makefile build file.  If this works then we should go the relative version throughout (in another set of changes).

2020-11-28 02:03 UTC, MikeCJohnsonUk commented on internal/config/InventoryReader_test.go
> +
Done

2020-11-28 02:04 UTC, MikeCJohnsonUk commented on internal/services/frontend/DBInventory.go
> +func InitDBInventory(ctx context.Context, cfg *config.GlobalConfig) (err error) {
In principle, yes I would agree. If there are no objection, I think I'd prefer to leave this to the next phase of these related changes.

2020-11-28 02:05 UTC, MikeCJohnsonUk commented on pkg/protos/inventory/external.proto
> +import "pkg/protos/common/capacity.proto";
Seems to be working so far. If after merging into master, they continue to work for everyone else, I'll fix this up globally.

2020-11-28 02:07 UTC, MikeCJohnsonUk commented on internal/config/InventoryReader.go
> +			Location:  "DC-PNW-0",
This was just an arbitrary string I added to make sure it has a recognizable value whilst debugging. I fully expect this will be sourced from the inventory defn yaml file at some point in the future.

Is this something that needs a change at this time?

2020-11-28 02:13 UTC, MikeCJohnsonUk commented on internal/services/frontend/DBInventory.go
> +func (m *DBInventory) ListBlades(ctx context.Context, zone string, rack string, options ...InventoryOption) (map[string]*DefinitionBlade, int64, error) {return nil, InvalidRev, nil}
Shortened, but while better, I'm still not really happy about how it ended up.

2020-11-28 02:20 UTC, MikeCJohnsonUk commented on internal/services/frontend/DBInventory_test.go
> +// 	assert := ts.Assert()
The approach I was planning has all changed, so for now I've removed these and something will take their place when the replacement loading logic is added.

Done.

2020-11-28 02:24 UTC, MikeCJohnsonUk commented on internal/services/frontend/frontend.go
>  	ts "github.com/Jim3Things/CloudChamber/internal/clients/timestamp"
Huh. I suspect these are remnants of a troubled merge that I failed to spot.

Fixed. (by removing the version on line 32.)

2020-11-28 02:27 UTC, MikeCJohnsonUk commented on pkg/protos/common/errors.go
> +// ErrInvalidItemSelf signals that the specified item has wired a port to itsel.
Done.

2020-11-28 15:17 UTC, Jim3Things commented on internal/config/InventoryReader.go
> +			Location:  "DC-PNW-0",
No, this can wait.

2020-11-28 15:25 UTC, Jim3Things approved these changes

2020-11-28 15:25 UTC, Jim3Things commented on internal/config/InventoryReader.go
> +		span.AddEvent(ctx, err.Error())
Seems to be

2020-11-29 01:47 UTC, merged