Moving decode to internal/common
Jim3Things/CloudChamber pull request #204
Opened 2021-01-25 13:32 UTC by manpreet85

26jan21

Created new branch.

Cut the two files and pasted into internal/common.

2021-01-25 15:22 UTC, Jim3Things requested changes
You need to change the package in the files.

Did you build the system after making the change?

2021-01-26 22:25 UTC, manpreet85 commented
Please help, i got 157 Problems after i changed the package to common.

If i build, would the problems disappear? Please advise

2021-01-26 22:42 UTC, Jim3Things commented
I'd suggest a make clean followed by a make build -j (after starting etcd), and see where that gets you.  Changing the package to match the package of common in these two files should not cause a bunch of new problems.

2021-02-07 03:25 UTC, Jim3Things approved these changes

2021-02-07 03:28 UTC, merged