Further conversion to generics, update to Go 1.19
Jim3Things/CloudChamber pull request #369
Opened 2022-09-13 17:53 UTC by Jim3Things

Most of this checkin is the result of a fresh go fmt on the project.  It has gotten even more opinionated than it was.  It won't say I like it, but go fmt is pretty much expected.  Better everyone's bad coding style than a good one, AFAICT.

The actual changes are for some remaining conversions to generics in the inventory client.

2022-09-14 01:57 UTC, MikeCJohnsonUk requested changes
I think the gofmt folks have lost the plot. They're removing blank comments to butt dissimilar constructs up against each other, and then start adding blank comments lines in the middle of sentences within a text block.

Can we please stop using this?

2022-09-14 01:57 UTC, MikeCJohnsonUk commented on simulation/internal/clients/inventory/api.go
> -//
You were probably expecting this, but for me, this is a big problem. Those comments were added specifically to make things readable when using non-colourizing editors. Removal introduces a readability issue. As such, I'm really not happy about this at all. 

If gofmt insists on doing this, I'd vote for ditching gofmt and it's unwanted opinions.

2022-09-14 01:57 UTC, MikeCJohnsonUk commented on simulation/internal/clients/inventory/leafViewsOfT.go
> +	return x != nil &&
Should it be legal to allow x to be nil?

cf. other functions, eg Load() below, there is no explicit nil test...

Is this one of those convention things?

2022-09-14 01:57 UTC, MikeCJohnsonUk commented on simulation/internal/clients/inventory/leafViewsOfT.go
> +		cov.CabledState.Equal(x) &&
Should we either commit to Equal() handling x being nil or not? I'd vote for not, but I could be convinced...

2022-09-14 01:57 UTC, MikeCJohnsonUk commented on simulation/internal/clients/inventory/pdu.go
> +			CabledState: NewCabledState[pb.PduState_SM](p.tables.Actual(), p),
Much cleaner.

2022-09-14 01:57 UTC, MikeCJohnsonUk commented on simulation/internal/services/frontend/db/users.go
>  //
Ah, another gofmt victim perhaps? Adding a blank comment in the middle of a paragraph?

2022-09-14 01:57 UTC, MikeCJohnsonUk commented on simulation/internal/services/frontend/workloads.go
> +//	held in a persisted store (Etcd)
Seriously?

2022-09-14 17:44 UTC, Jim3Things commented on simulation/internal/clients/inventory/api.go
> -//
I've reverted the files that weren't otherwise changed in the generics work.  That does leave some of the trailing blank comments removed.  I'm honestly not sure what to do about go fmt overall.

2022-09-14 17:46 UTC, Jim3Things commented on simulation/internal/clients/inventory/leafViewsOfT.go
> +	return x != nil &&
Probably the right check is to say that either x is not nil, or both are nil.  And load probably should set the values to defaults if the source is nil.  I'll update all with the next commit on this thread.

2022-09-14 17:47 UTC, Jim3Things commented on simulation/internal/clients/inventory/leafViewsOfT.go
> +		cov.CabledState.Equal(x) &&
There's a common case where there is no prior state and we're trying to see if this state is the same.  Alllowing nil to be passed makes that easier at the calls site(s).

2022-09-14 17:47 UTC, Jim3Things commented on simulation/internal/services/frontend/db/users.go
>  //
reverted.

2022-09-14 17:47 UTC, Jim3Things commented on simulation/internal/services/frontend/workloads.go
> +//	held in a persisted store (Etcd)
reverted.

2022-09-16 15:54 UTC, Jim3Things commented on simulation/internal/clients/inventory/leafViewsOfT.go
> +	return x != nil &&
I've decided to leave load alone, but have fixed the equal calls.

2022-09-17 00:19 UTC, MikeCJohnsonUk approved these changes

2022-09-17 00:19 UTC, MikeCJohnsonUk commented on simulation/internal/clients/store/TestSuiteCore.go
> +	initialized  bool = false
Just a heads up: I'm happy with this either way, but it looks like a valid change that got reverted. Your call whether or not to accept the original modification.

2022-09-17 00:19 UTC, MikeCJohnsonUk commented on simulation/internal/common/decode.go
> +	var test []string = strings.Split(source, ",")
Another valid change that got reverted? I'm happy either way. Your call.

2022-09-17 14:39 UTC, Jim3Things commented on simulation/internal/clients/store/TestSuiteCore.go
> +	initialized  bool = false
Yes, they were in a file I'd otherwise touched.  Since it is logically the same, I reverted down to the files I touched.  Same for the next one.

2022-09-17 14:39 UTC, merged